// Login User
export const FETCH_LOGIN_REQUEST_TRIGGERED = 'FETCH_LOGIN_REQUEST_TRIGGERED';
export const FETCH_LOGIN_REQUEST_SUCCESS = 'FETCH_LOGIN_REQUEST_SUCCESS';
export const FETCH_LOGIN_REQUEST_FAILURE = 'FETCH_LOGIN_REQUEST_FAILURE';

// Create New user
export const CREATE_USER_REQUEST_TRIGGERED = 'CREATE_USER_REQUEST_TRIGGERED';
export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_REQUEST_FAILURE = 'CREATE_USER_REQUEST_FAILURE';

// Fetch user info
export const FETCH_USER_INFO_TRIGGERED = 'FETCH_USER_INFO_TRIGGERED';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// Create new list

export const CREATE_LIST_TRIGGERED = 'CREATE_LIST_TRIGGERED';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';
