// Login User
export const FETCH_LOGIN_REQUEST_TRIGGERED = 'FETCH_LOGIN_REQUEST_TRIGGERED';
export const FETCH_LOGIN_REQUEST_SUCCESS = 'FETCH_LOGIN_REQUEST_SUCCESS';
export const FETCH_LOGIN_REQUEST_FAILURE = 'FETCH_LOGIN_REQUEST_FAILURE';

// Create New user
export const CREATE_USER_REQUEST_TRIGGERED = 'CREATE_USER_REQUEST_TRIGGERED';
export const CREATE_USER_REQUEST_SUCCESS = 'CREATE_USER_REQUEST_SUCCESS';
export const CREATE_USER_REQUEST_FAILURE = 'CREATE_USER_REQUEST_FAILURE';

// Fetch user info
export const FETCH_USER_INFO_TRIGGERED = 'FETCH_USER_INFO_TRIGGERED';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

// Modal
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// Create new list
export const CREATE_LIST_TRIGGERED = 'CREATE_LIST_TRIGGERED';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

// Fetch users lists
export const FETCH_USERS_LISTS_TRIGGERED = 'FETCH_USERS_LISTS_TRIGGERED';
export const FETCH_USERS_LISTS_SUCCESS = 'FETCH_USERS_LISTS_SUCCESS';
export const FETCH_USERS_LISTS_FAILURE = 'FETCH_USER_LISTS_FAILURE';

// Fetch users shared lists
export const FETCH_USERS_SHARED_LISTS_TRIGGERED = 'FETCH_USERS_SHARED_LISTS_TRIGGERED';
export const FETCH_USERS_SHARED_LISTS_SUCCESS = 'FETCH_USERS_SHARED_LISTS_SUCCESS';
export const FETCH_USERS_SHARED_LISTS_FAILURE = 'FETCH_USERS_SHARED_LISTS_FAILURE';

// Fetch list by id
export const FETCH_LIST_BY_ID_TRIGGERED = 'FETCH_LIST_BY_ID_TRIGGERED';
export const FETCH_LIST_BY_ID_SUCCESS = 'FETCH_LIST_BY_ID_SUCCESS';
export const FETCH_LIST_BY_ID_FAILURE = 'FETCH_LIST_BY_ID_FAILURE';

// Clear current list
export const CLEAR_CURRENT_LIST = 'CLEAR_CURRENT_LIST';

// Delete project
export const DELETE_LIST_TRIGGERED = 'DELETE_LIST_TRIGGERED';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

// Update project
export const UPDATE_LIST_TRIGGERED = 'UPDATE_LIST_TRIGGERED';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE';

// Logout clear user
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

// Clear current lists
export const CLEAR_ALL_CURRENT_LISTS = 'CLEAR_ALL_CURRENT_LISTS';
